Code quality/increase coverage of firmware management service
MithraicMagic/open-smart-grid-platform pull request #8
Opened 2020-09-24 13:10 UTC by andrevanduin

2020-09-24 13:12 UTC, arjen0203 commented on osgp/platform/osgp-adapter-domain-core/src/main/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementService.java
> +            LOGGER.error("Caught exception when creating pending firmware update record for SSLD: {}",
INSANE FIX

2020-09-24 13:53 UTC, arjen0203 reviewed
looks good

2020-09-24 14:15 UTC, HighCrit commented on osgp/platform/osgp-adapter-domain-core/src/test/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementServiceTest.java
> +		final ResponseMessage responseMessage = this.responseMessageCaptor.getValue();
Hele gekke indentations jonge man

2020-09-24 14:16 UTC, HighCrit requested changes

2020-09-24 14:16 UTC, HighCrit commented on osgp/platform/osgp-adapter-domain-core/src/test/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementServiceTest.java
> +
Hele gekke indentations jonge man

2020-10-06 08:40 UTC, HighCrit approved these changes

2020-12-15 08:46 UTC, merged